name: Slash Commands

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: ${{ github.event.issue.pull_request }}
    name: Check comments for /deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          command: deploy
          reaction: "false"
          repo-token: ${{ secrets.GHA_TOKEN }}
      - name: Dispatch Workflow
        if: steps.command.outputs.command-name == 'deploy'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
          gh workflow run workflow-dispatch.yml --ref ${{ steps.comment-branch.outputs.head_ref }} -f author=${{ github.event.issue.user.login }} -f pr_number=${{ github.event.issue.number }}

