name: Slash Commands

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: ${{ github.event.issue.pull_request }}
    name: Check comments for /deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          command: deploy
          reaction: "false"
          repo-token: ${{ secrets.GHA_TOKEN }}
      - name: Dispatch Workflow
        if: steps.command.outputs.command-name == 'deploy'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}

          echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
          echo '{ "pr_number": ${{ github.event.issue.number }}, "author": ${{ github.event.issue.user.login }} }' | gh workflow run workflow-dispatch.yml --json --ref ${{ github.ref }}

